FROM quay.io/thoth-station/s2i-lab-elyra:v0.2.1

USER root

RUN pip install pip==22.2.2 setuptools==65.3.0

# uncomment following line if working in an air-gapped environment
# RUN pip uninstall -y jupyterlab-tabnine

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

USER 8888
