FROM registry.access.redhat.com/ubi8/python-38

USER root

RUN dnf -y update \
 && dnf -y install python3-pip \
 && dnf -y clean all \
 && rm -rf /var/cache/dnf \
 && pip install pip==23.1.2 setuptools==67.8.0

USER 1001

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
