FROM quay.io/mmurakam/model-cars:modelcar-builder-v0.1.0 as builder

RUN python3 -c "\
from huggingface_hub import snapshot_download; \
snapshot_download(repo_id='thegshipley/fluxcapacitor', revision='8f507a11091d3adc076df356e914e3d10fb3d764', local_dir='/models', allow_patterns=['*.safetensors', '*.json', '*.txt']);"

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

COPY --from=builder /models /models

USER 1001