# Base image for the modelcar Granite image
FROM quay.io/mmurakam/model-cars:modelcar-builder-v0.1.0

RUN python3 -c "\
from huggingface_hub import snapshot_download; \
snapshot_download(repo_id='thegshipley/fluxcapacitor', revision='8f507a11091d3adc076df356e914e3d10fb3d764', local_dir='/models', allow_patterns=['*.safetensors', '*.json', '*.txt']);"

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4  

# Set the user to 1001
USER 1001