FROM quay.io/modh/odh-pytorch-notebook:v2-2024a-20240628-ac07414

RUN pip install pip==22.3.1 setuptools==65.3.0

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    pip uninstall -y ray && \
    chmod -R g+w /opt/app-root/lib/python3.9/site-packages && \
    fix-permissions /opt/app-root -P
