FROM quay.io/opendatahub/workbench-images:runtime-pytorch-ubi9-python-3.9-f93694f

RUN pip install pip==22.3.1 setuptools==65.3.0

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
