kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: s2i-custom-notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image containing dependencies for custom ML project
    opendatahub.io/notebook-image-name: custom notebook image
    opendatahub.io/notebook-image-url: 'https://github.com/mamurak/odh-pachyderm-pipelines.git'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: jupyter
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"matplotlib","version":"3.5.2"},{"name":"numpy","version":"1.22.4"},{"name":"pandas","version":"1.4.3"},{"name":"scipy","version":"1.9.0"},{"name":"scikit-learn","version":"1.1.2"},{"name":"scikit-plot","version":"0.3.7"},{"name":"feature-engine","version":"1.4.1"},{"name":"imbalanced-learn","version":"0.9.1"},{"name":"shap","version":"0.41.0"},{"name":"trino","version":"0.315.0"}]
        opendatahub.io/notebook-software: >-
          [{"name":"Python","version":"3.8.6"},{"name":"Pachctl","version":"2.2.7"}]
      from:
        kind: ImageStreamImage
        name: >-
          sha256:6f5c484da9d62d43976312402f75c95277e53b9b350b4bce7da53ffd3b462234
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
