train: /opt/app-root/src/os-mlops/notebooks/object-detection-example/model-training/data/images/train
val:   /opt/app-root/src/os-mlops/notebooks/object-detection-example/model-training/data/images/val
test:  /opt/app-root/src/os-mlops/notebooks/object-detection-example/model-training/data/images/test

names: ['Traffic sign']