FROM quay.io/modh/odh-pytorch-notebook:v3-2024b-20241111

USER root

RUN dnf install -y tesseract tesseract-devel tesseract-langpack-eng leptonica-devel && \
    TESSDATA_PREFIX=/usr/share/tesseract/tessdata/ && \
    echo "Set TESSDATA_PREFIX=${TESSDATA_PREFIX}" && \
    pip install --no-cache-dir docling && \
    fix-permissions /opt/app-root -P

USER 1001