FROM quay.io/modh/codeserver:codeserver-ubi9-python-3.9-2023b-20240124-ef31e06

RUN pip install pip==22.3.1 setuptools==65.3.0

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
