FROM quay.io/opendatahub/workbench-images:cuda-jupyter-datascience-ubi9-python-3.9-20230706

RUN pip install pip==22.3.1 setuptools==65.3.0

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
