FROM quay.io/mmurakam/rstudio-cuda-base:rstudio-cuda-base-v0.1.0

USER root

# R packages

RUN yum install -y R-base64enc && \
    R -q -e 'install.packages(c("keras", "tidyverse", "remotes", "mlflow", "torch", "devtools", "tesseract", "BiocManager", "Shiny", "carat", "e1071", "igraph", "ROCR", "randomForest", "tm"))'

USER 8888
