FROM quay.io/modh/odh-pytorch-notebook@sha256:1b6ec48247f15613d452d2972595b54c4160a0607330396ff5bf88e2140380f3

RUN pip install pip==22.3.1 setuptools==65.3.0

USER 1001

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    chmod -R g+w /opt/app-root/lib/python3.9/site-packages && \
    fix-permissions /opt/app-root -P
