FROM quay.io/modh/odh-generic-data-science-notebook:v3-2024b-20241004-69688c1

RUN pip install --upgrade pip==24.3.1 setuptools==75.3.0

RUN pip install --no-cache-dir jupyter-collaboration>=1.0.0a0 
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P
