FROM quay.io/thoth-station/s2i-minimal-py38-notebook:v0.5.1

ENV PACHCTL_VERSION 2.4.2
ENV JUPYTERLAB_PACHYDERM_VERSION 2.4.2

USER root
RUN mkdir -p /pfs \
 && chmod 1777 /pfs

RUN dnf -y update \
 && dnf -y install curl fuse \
 && dnf -y clean all \
 && rm -rf /var/cache/dnf \
 && echo "user_allow_other" | tee -a /etc/fuse.conf > /dev/null \
 && curl -f -o pachctl.tar.gz -L https://github.com/pachyderm/pachyderm/releases/download/v${PACHCTL_VERSION}/pachctl_${PACHCTL_VERSION}_linux_amd64.tar.gz \
 && tar zxfv pachctl.tar.gz && mv pachctl_${PACHCTL_VERSION}_linux_amd64/pachctl /usr/local/bin/ \
 && curl -f -o mount-server.tar.gz -L https://github.com/pachyderm/pachyderm/releases/download/v${JUPYTERLAB_PACHYDERM_VERSION}/mount-server_${JUPYTERLAB_PACHYDERM_VERSION}_linux_amd64.tar.gz \
 && tar zxfv mount-server.tar.gz && mv mount-server_${JUPYTERLAB_PACHYDERM_VERSION}_linux_amd64/mount-server /usr/local/bin/

USER 8888
RUN pip install --upgrade pip

USER root

RUN mkdir /app
WORKDIR /app
COPY /scripts/config.sh .
RUN chmod +x config.sh

#USER 8888

RUN pip install --no-cache-dir jupyterlab-pachyderm==${JUPYTERLAB_PACHYDERM_VERSION} python-pachyderm==7.3.3
