FROM quay.io/thoth-station/s2i-minimal-py38-notebook:v0.5.1

ENV PACHCTL_VERSION 2.4.2
ENV JUPYTERLAB_PACHYDERM_VERSION 2.4.2

USER root
RUN dnf -y update \
 && dnf -y install curl \
 && dnf -y clean all \
 && rm -rf /var/cache/dnf \
 && curl -f -o pachctl.tar.gz -L https://github.com/pachyderm/pachyderm/releases/download/v${PACHCTL_VERSION}/pachctl_${PACHCTL_VERSION}_linux_amd64.tar.gz \
 && tar zxfv pachctl.tar.gz && mv pachctl_${PACHCTL_VERSION}_linux_amd64/pachctl /usr/local/bin/

USER 8888
RUN pip install --upgrade pip \
 && pip install --no-cache-dir jupyterlab-pachyderm==${JUPYTERLAB_PACHYDERM_VERSION} python-pachyderm==7.3.3
