apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db
  namespace: rhoai-model-registries
stringData:
  database-name: "model_registry"
  database-password: "TheBlurstOfTimes" # notsecret
  database-user: "mlmduser" # notsecret
---
apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/display-name: model-registry
  name: model-registry
  namespace: rhoai-model-registries
spec:
  grpc:
    port: 9090
  mysql:
    database: model_registry
    host: model-registry-db.mysql.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db
    port: 3306
    skipDBCreation: false
    username: mlmduser
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    serviceRoute: disabled