FROM quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-minimal-ubi8-py38_2023b_latest

ENV JUPYTER_ENABLE_LAB=true
ENV CRIO_RUNTIME=true

WORKDIR /opt/app-root/bin

RUN pip install pip==22.3.1 setuptools==65.3.0

# uncomment following line if working in an air-gapped environment
# RUN pip uninstall -y jupyterlab-tabnine

COPY setup-elyra.sh start-notebook.sh requirements.txt ./

RUN pip install --no-cache-dir -r ./requirements.txt && \
    chmod -R g+w /opt/app-root/lib/python3.8/site-packages && \
    fix-permissions /opt/app-root -P

# environment variables used for Elyra runtime setup at runtime
ENV KF_DEPLOYMENT_NAMESPACE=${KF_DEPLOYMENT_NAMESPACE:-redhat-ods-applications}
ENV S3_ENDPOINT_URL=${S3_ENDPOINT_URL:-http://minio-service.minio.svc.cluster.local:9000}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minio}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minio123}
ENV COS_BUCKET=${COS_BUCKET:-elyra}

