FROM quay.io/thoth-station/s2i-minimal-py38-notebook:v0.5.1

ENV JUPYTER_ENABLE_LAB=true
ENV CRIO_RUNTIME=true

WORKDIR /opt/app-root/bin

RUN pip install pip==22.2.2 setuptools==65.3.0

# uncomment following line if working in an air-gapped environment
# RUN pip uninstall -y jupyterlab-tabnine

COPY setup-elyra.sh start-notebook.sh requirements.txt ./

RUN pip install --no-cache-dir -r ./requirements.txt && \
    chmod -R g+w /opt/app-root/lib/python3.8/site-packages && \
    fix-permissions /opt/app-root -P
