FROM quay.io/thoth-station/s2i-minimal-py38-notebook:v0.5.1

ENV JUPYTER_ENABLE_LAB=true
ENV CRIO_RUNTIME=true

WORKDIR /opt/app-root/bin

RUN pip install pip==22.2.2 setuptools==65.3.0 && \
    curl -f -o miniconda.sh -L https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh && \
    /bin/sh miniconda.sh -b -p /opt/app-root -u && \
    conda install -y -c conda-forge/label/main yarn && \
    git clone https://github.com/mamurak/elyra.git && \
    cd elyra && \
    make clean install && \
    jupyter labextension list

# uncomment following line if working in an air-gapped environment
# RUN pip uninstall -y jupyterlab-tabnine

COPY setup-elyra.sh start-notebook.sh requirements.txt ./

RUN pip install --no-cache-dir -r ./requirements.txt && \
    chmod -R g+w /opt/app-root/lib/python3.8/site-packages && \
    fix-permissions /opt/app-root -P
